name: Build and Deploy
on:
  push:
    branches: 
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@releases/latest
      - name: Deploy
        uses: thetif/ReactMatchingGame@releases/latest
        with:
          REACT_APP_MATCH_API_KEY: ${{ secrets.REACT_APP_MATCH_API_KEY }}
          BASE_BRANCH: master 
          BRANCH: gh-pages
          FOLDER: build
        
