name: Build and Deploy
on:
  push:
    branches: 
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and Deploy
        uses: thetif/ReactMatchingGame@v1
        with:
          REACT_APP_MATCH_API_KEY: ${{ secrets.REACT_APP_MATCH_API_KEY }}
          BASE_BRANCH: master 
          BRANCH: gh-pages
          FOLDER: build
        
